export const IN_LOADING = 'IN_LOADING';
export const END_LOADING = 'END_LOADING';
export const TV_SHOW_ADDED_IN_COLLECTION = 'TV_SHOW_ADDED_IN_COLLECTION';
export const TV_SHOW_REMOVED_FROM_COLLECTION =
  'TV_SHOW_REMOVED_FROM_COLLECTION';
export const EPISODE_SEEN = 'EPISODE_SEEN';
export const EPISODE_NOT_SEEN = 'EPISODE_NOT_SEEN';
