export const IN_LOADING = 'IN_LOADING';
export const END_LOADING = 'END_LOADING';
export const COLLECTION_ADD_TV_SHOW = 'COLLECTION_ADD_TV_SHOW';
export const COLLECTION_REMOVE_TV_SHOW = 'COLLECTION_REMOVE_TV_SHOW';
export const COLLECTION_WATCHED_EPISODES = 'COLLECTION_WATCHED_EPISODES';
export const COLLECTION_NOT_WATCHED_EPISODES = 'COLLECTION_NOT_WATCHED_EPISODES';
