export const COLLECTION_ADD_TV_SHOW = 'COLLECTION_ADD_TV_SHOW';
export const COLLECTION_REMOVE_TV_SHOW = 'COLLECTION_REMOVE_TV_SHOW';
export const COLLECTION_WATCHED_EPISODES = 'COLLECTION_WATCHED_EPISODES';
export const COLLECTION_NOT_WATCHED_EPISODES = 'COLLECTION_NOT_WATCHED_EPISODES';
export const COLLECTION_REFRESH = 'COLLECTION_REFRESH';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
